/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ajaxie.lastfm;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int alert_dialog_icon=0x7f020000;
        public static final int ban=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int love=0x7f020003;
        public static final int play=0x7f020004;
        public static final int play_small=0x7f020005;
        public static final int share=0x7f020006;
        public static final int skip=0x7f020007;
        public static final int stop=0x7f020008;
    }
    public static final class id {
        public static final int album_name_text=0x7f050004;
        public static final int album_view=0x7f050002;
        public static final int ban_button=0x7f05000b;
        public static final int cancel_button=0x7f050011;
        public static final int creator_name_text=0x7f050003;
        public static final int love_button=0x7f05000a;
        public static final int ok_button=0x7f050012;
        public static final int password=0x7f050014;
        public static final int play_button=0x7f050007;
        public static final int share_button=0x7f05000c;
        public static final int share_track_author=0x7f05000d;
        public static final int share_track_message=0x7f050010;
        public static final int share_track_recipient=0x7f05000f;
        public static final int share_track_title=0x7f05000e;
        public static final int skip_button=0x7f050009;
        public static final int station_url=0x7f050001;
        public static final int status_text=0x7f050000;
        public static final int stop_button=0x7f050008;
        public static final int time_counter=0x7f050006;
        public static final int track_name_text=0x7f050005;
        public static final int username=0x7f050013;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int sharetrack=0x7f030001;
        public static final int userinfo=0x7f030002;
    }
    public static final class string {
        public static final int alert_dialog_ok=0x7f040005;
        public static final int alert_dialog_single_choice=0x7f040004;
        public static final int app_name=0x7f040001;
        public static final int cancel_button=0x7f040008;
        public static final int hello=0x7f040000;
        public static final int local_service_connected=0x7f040002;
        public static final int local_service_disconnected=0x7f040003;
        public static final int menu_settings=0x7f04000a;
        public static final int ok_button=0x7f040007;
        public static final int settings_button=0x7f040009;
        public static final int share_track_title=0x7f04000b;
        public static final int user_info_title=0x7f040006;
    }
}
