/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ajaxie.lastfm;

public final class R {
    public static final class array {
        public static final int station_types=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int alert_dialog_icon=0x7f020000;
        public static final int ban=0x7f020001;
        public static final int btn_radio_on=0x7f020002;
        public static final int expander_ic_maximized=0x7f020003;
        public static final int expander_ic_minimized=0x7f020004;
        public static final int icon=0x7f020005;
        public static final int lastfm_icon=0x7f020006;
        public static final int loadinfo_001=0x7f020007;
        public static final int loadinfo_002=0x7f020008;
        public static final int loadinfo_003=0x7f020009;
        public static final int loadinfo_004=0x7f02000a;
        public static final int loadinfo_005=0x7f02000b;
        public static final int loadinfo_006=0x7f02000c;
        public static final int loadinfo_007=0x7f02000d;
        public static final int loadinfo_008=0x7f02000e;
        public static final int loadinfo_009=0x7f02000f;
        public static final int loadinfo_010=0x7f020010;
        public static final int loadinfo_011=0x7f020011;
        public static final int loadinfo_012=0x7f020012;
        public static final int loadinfo_013=0x7f020013;
        public static final int loadinfo_014=0x7f020014;
        public static final int loadinfo_015=0x7f020015;
        public static final int loadinfo_016=0x7f020016;
        public static final int loading_animation=0x7f020017;
        public static final int love=0x7f020018;
        public static final int play=0x7f020019;
        public static final int play_small=0x7f02001a;
        public static final int share=0x7f02001b;
        public static final int skip=0x7f02001c;
        public static final int stop=0x7f02001d;
        public static final int tune_icon=0x7f02001e;
    }
    public static final class id {
        public static final int album_name_text=0x7f06000c;
        public static final int album_view=0x7f06000a;
        public static final int ban_button=0x7f060016;
        public static final int cancel_button=0x7f060004;
        public static final int container=0x7f06001d;
        public static final int creator_name_text=0x7f06000b;
        public static final int error_text=0x7f060018;
        public static final int label=0x7f060002;
        public static final int loading_container=0x7f06000f;
        public static final int loading_image=0x7f060010;
        public static final int loading_text=0x7f060011;
        public static final int love_button=0x7f060015;
        public static final int ok_button=0x7f060005;
        public static final int password=0x7f060020;
        public static final int play_button=0x7f060012;
        public static final int radio_name=0x7f060007;
        public static final int reset_button=0x7f060001;
        public static final int selected=0x7f060021;
        public static final int share_button=0x7f060017;
        public static final int share_track_author=0x7f06001a;
        public static final int share_track_message=0x7f06001c;
        public static final int share_track_recipient=0x7f06001b;
        public static final int share_track_title=0x7f060019;
        public static final int skip_button=0x7f060014;
        public static final int station_name=0x7f060003;
        public static final int station_type_list=0x7f06001e;
        public static final int status_text=0x7f060006;
        public static final int stop_button=0x7f060013;
        public static final int switcher=0x7f060009;
        public static final int time_counter=0x7f06000e;
        public static final int track_name_text=0x7f06000d;
        public static final int tune_button=0x7f060008;
        public static final int username=0x7f06001f;
        public static final int version=0x7f060000;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int enter_station=0x7f030001;
        public static final int enter_tag=0x7f030002;
        public static final int main=0x7f030003;
        public static final int sharetrack=0x7f030004;
        public static final int tune=0x7f030005;
        public static final int userinfo=0x7f030006;
    }
    public static final class string {
        public static final int about_title=0x7f05000e;
        public static final int alert_dialog_cancel=0x7f050006;
        public static final int alert_dialog_ok=0x7f050005;
        public static final int alert_dialog_single_choice=0x7f050004;
        public static final int app_name=0x7f050001;
        public static final int cancel_button=0x7f050009;
        public static final int enter_artist_name_title=0x7f05001a;
        public static final int enter_station_title=0x7f050019;
        public static final int enter_tag_title=0x7f05001b;
        public static final int hello=0x7f050000;
        public static final int local_service_connected=0x7f050002;
        public static final int local_service_disconnected=0x7f050003;
        public static final int menu_about=0x7f05000d;
        public static final int menu_settings=0x7f05000b;
        public static final int message=0x7f050016;
        public static final int ok_button=0x7f050008;
        public static final int password=0x7f050011;
        public static final int settings_button=0x7f05000a;
        public static final int share_track_title=0x7f05000c;
        public static final int signup=0x7f050012;
        public static final int station_spinner_prompt=0x7f05000f;
        public static final int track_banned=0x7f050014;
        public static final int track_loved=0x7f050013;
        public static final int track_shared=0x7f050015;
        public static final int tune=0x7f050018;
        public static final int user_info_title=0x7f050007;
        public static final int username=0x7f050010;
        public static final int with=0x7f050017;
    }
}
